apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbltkjc4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iot-web
  template:
    metadata:
      labels:
        app: iot-web
    spec:
      containers:
        - name: iot-web-container
          image: fahrurozid/iot-klp4:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always